import 'dart:convert';
import 'package:register_form/models/album.dart';
import 'package:http/http.dart' as http;

final String jsonplaceholder = "http://jsonplaceholder.typicode.com/users/";

//Future method to read the URL
Future<Autogenerated> fetchInfo() async{
  final response = await http.get(jsonplaceholder);
  final jsonresponse = json.decode(response.body);

  // List<Users> posts = List<Users>.from(l.map((model)=> Users.fromJson(model)));

  return Autogenerated.fromJson(jsonresponse[0]);
}
