class Autogenerated {
  final int userID;
  final String name;
  final String username;
  final String email;
  final Address address;

  Autogenerated({this.userID, this.name, this.username, this.email, this.address});

  factory Autogenerated.fromJson(Map<String, dynamic> usersjson)=> Autogenerated(
      userID: usersjson["id"],
      name: usersjson["name"],
      username: usersjson["username"],
      email: usersjson["email"],
      address: Address.fromJson(usersjson["address"])
  );
}

class Address{

  final String street;
  final String suite;
  final String city;
  final String zipcode;

  Address({this.street, this.suite, this.city, this.zipcode});

  factory Address.fromJson(Map<String, dynamic> addjson){

    return Address(
        street: addjson["street"],
        suite:  addjson["suite"],
        city: addjson["city"],
        zipcode: addjson["zipcode"]
    );
  }
}