import 'package:flutter/material.dart';
import 'package:register_form/models/album.dart';
import 'package:register_form/services/user_data.dart';

class User extends StatefulWidget {
   @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<User> {
  Future<Autogenerated> futureAlbum;

  @override
  void initState() {
    super.initState();
    futureAlbum = fetchInfo();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fetch Data',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Scaffold(
        appBar: AppBar(
          title: Text('Fetch Data'),
        ),
        body: Column(
          children: [
             FutureBuilder<Autogenerated>(
                future: futureAlbum,
                builder: (context, snapshot) {
                  if (snapshot.hasData) {
                    return Card(
                      elevation: 4,
                      child: ListTile(
                        title: Text(snapshot.data.name),
                        subtitle: Text(snapshot.data.email),
                      )
                    );
                  } else if (snapshot.hasError) {
                    return Text("${snapshot.error}");
                  }
                  // By default, show a loading spinner.
                  return CircularProgressIndicator();
                },
              ),
          ],
        ),
      ),
    );
  }
}